export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const GET_MY_RESERVATIONS = 'GET_MY_RESERVATIONS';
export const ADD_NEW_RESERVATION = 'ADD_NEW_RESERVATION';
