export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const LOAD_HOUSES = 'LOAD_HOUSES';
export const GET_MY_RESERVATIONS = 'GET_MY_RESERVATIONS';
export const NEW_HOUSE = 'NEW_HOUSE';
export const GET_HOUSE = 'GET_HOUSE';
